"""add profile taxonomy and sharing

Revision ID: a1c112a4608c
Revises: 
Create Date: 2026-04-24 18:17:31.585836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c112a4608c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_semester_id'), 'subjects', ['semester_id'], unique=False)
    op.add_column('notes', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('notes', sa.Column('semester_id', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_notes_semester_id'), 'notes', ['semester_id'], unique=False)
    op.create_index(op.f('ix_notes_share_token'), 'notes', ['share_token'], unique=True)
    op.create_index(op.f('ix_notes_subject_id'), 'notes', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'notes', 'semesters', ['semester_id'], ['id'])
    op.create_foreign_key(None, 'notes', 'subjects', ['subject_id'], ['id'])
    op.add_column('users', sa.Column('display_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('college', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'college')
    op.drop_column('users', 'department')
    op.drop_column('users', 'display_name')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_subject_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_share_token'), table_name='notes')
    op.drop_index(op.f('ix_notes_semester_id'), table_name='notes')
    op.drop_column('notes', 'share_token')
    op.drop_column('notes', 'subject_id')
    op.drop_column('notes', 'semester_id')
    op.drop_column('notes', 'description')
    op.drop_index(op.f('ix_subjects_semester_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('semesters')
    # ### end Alembic commands ###
